### ISSUE TITLE
Improve the popup sheet

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#1]
Redesign the extension popup sheet. It currently looks something like this in the unsaved and saved state respectively -

![image](https://user-images.githubusercontent.com/21277179/66234301-feadc100-e70a-11e9-9073-ac32f8751346.png) ![image](https://user-images.githubusercontent.com/21277179/66234336-17b67200-e70b-11e9-8e7b-896a469a8719.png)

You can find the HTML and CSS for it in [`popup.js`](https://github.com/devfolioco/scrroll-in/blob/f782ac9503acc43d49a3660d8c14fcb68a6d9522/popup.js#L9-L18) and [`popup.css`](https://github.com/devfolioco/scrroll-in/blob/master/popup.css)

**Comment by KarlaChen** [comment]
Hi, @prateek3255 . Can I try it?

**Comment by prateek3255** [comment]
Yes, @KarlaChen go ahead! 😃

**Comment by prateek3255** [comment]
This issue is still open for taking up if anyone's interested.

**Comment by prateek3255** [comment]
Please refer #35
