### ISSUE TITLE
Add percentage completion in the options page

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#10]
The options page currently shows all the pages whose scroll positions have been saved. 

![image](https://user-images.githubusercontent.com/21277179/66236258-a4632f00-e70f-11e9-85e7-bf4250cc2b44.png)

It can be improved to show the amount of the page that is completed in form of percentage or progress bar.

For this, you'll need to store the total scrollable length of the page as well while storing the scroll position as well.

**Comment by shikharsaxena98** [comment]
Hey, I want to work on this issue.

**Comment by shikharsaxena98** [comment]
I think we can close this now.

**Comment by prateek3255** [comment]
Yeah right, forgot to close this. Thanks again @shikharsaxena98 👍
