### ISSUE TITLE
Suggestion to change settings icon

### ISSUE THREAD

**Issue by sharur7** [devfolioco/scrroll-in#113]
**Is your feature request related to a problem? Please describe.**
The new extension has a settings icon which on clicking takes to the saved scrolls. Suggestion from my side if the icon is changed to some other icon which shows that there are saved scrolls then that would be good for users. 

**Describe the solution you'd like**
The settings icon can be changed to a Saved icon.

**Additional context**

Settings icon
<img src="https://user-images.githubusercontent.com/57194200/95017970-1602ef80-067a-11eb-89de-e779a6e8bc4c.png" width = 30 height = 30 >

Saved icon
<img src="https://user-images.githubusercontent.com/57194200/95017969-14d1c280-067a-11eb-83cb-9fa91c626094.png" width = 30 height = 30 >

@prateek3255 Tell me if its a valid change or not. I would like to work on this issue

**Comment by prateek3255** [comment]
Makes sense, please go ahead and replace the icon.
