### ISSUE TITLE
Add issue labeller and greeting github action 

### ISSUE THREAD

**Issue by bislara** [devfolioco/scrroll-in#114]
Add issue labeller action to add relevant labels to the issues once created. 

Add GitHub action to greet a first-time contributor for an issue or a PR.

**Comment by thisHermit** [comment]
Hey @bislara, can I work on it?

**Comment by bislara** [comment]
@thisHermit  Hey I created this issue so that I can work on it.

**Comment by prateek3255** [comment]
You can open a PR I will take a look, and merge it if it makes sense

**Comment by bislara** [comment]
@prateek3255  Kindly check once and let me know the review of it.
