### ISSUE TITLE
some links are broken in README.md

### ISSUE THREAD

**Issue by two-ticks** [devfolioco/scrroll-in#147]
**Describe the bug**
Some links are broken in README.md 

**To Reproduce**
1. Go to 'README.md '
2. Scroll down 
3. See error

**Expected behavior**
Scrroll logo should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/68433541/112745898-41cbb600-8fc9-11eb-9c8a-8362ab6aa7a6.png)

**Comment by prateek3255** [comment]
@two-ticks Feel free to open a PR to fix it
