### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Parikshit-Hooda** [devfolioco/scrroll-in#18]
**Is your feature request related to a problem? Please describe.**
A test suite for the project would be nice. I am learning to write tests, so this would be a great experience.

**Describe the solution you'd like**
A test suite written in one of the popular frameworks like mocha, chai

**Describe alternatives you've considered**

**Additional context**

**Comment by Parikshit-Hooda** [comment]
If we plan to go ahead with it, assign this issue to me.

**Comment by prateek3255** [comment]
Yeah, I was going to open an issue for tests. Go ahead!

**Comment by Parikshit-Hooda** [comment]
@prateek3255 lets use [this](https://github.com/jasmine/jasmine) framework!

**Comment by itaditya** [comment]
@Parikshit-Hooda if you want to get up and running quickly then use jest. It is the easiest to setup and it's DX is great.

**Comment by prateek3255** [comment]
Feel free to use whatever you feel comfortable with. I would prefer jest BTW.

**Comment by shikharsaxena98** [comment]
Any update on this? @Parikshit-Hooda

**Comment by Parikshit-Hooda** [comment]
shall be pushing in a day or two. I have decided to go with jest, as suggested by @prateek3255 
@shikharsaxena98 Do you have any suggestions of which functionalities should I test? You can help this way!

**Comment by Parikshit-Hooda** [comment]
@itaditya @prateek3255  I can't find the docs to implement jest testing on the browser side. If you know how to do so, please point me in the right direction. In the meantime, I have started building the tests with mocha-chai. If you want, check the progress [here](https://github.com/perry-contribs/scrroll-in/tree/mochatest1). @prateek3255 I am ready to merge this starter with adequate docs if you wish.

**Comment by prateek3255** [comment]
No, worries @Parikshit-Hooda you can go ahead with mocha-chai if you feel comfortable with it. Once you add a few valid test cases, we can start merging it.

**Comment by Parikshit-Hooda** [comment]
@prateek3255 @shikharsaxena98 I would like to be taken off this issue. I have been caught up with something else.

**Comment by king-11** [comment]
@akashnimare can I work on this issue also please do tell which framework shall I go forward with?

**Comment by BhuwanChandra** [comment]
@akashnimare I would like to work on this issue, please assign this to me!!
