### ISSUE TITLE
Update the extension icon

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#2]
Design and add a new icon for the extension.

Please post the suggestions on this issue first.

We'll be needing an active and inactive state icon of the following dimensions -
16x16, 32x32, 48x48, 128x128 and 256x256

Here's the current active icon -
https://github.com/devfolioco/scrroll-in/blob/master/images/favicon-384x384.png

and the inactive icon - 
https://github.com/devfolioco/scrroll-in/blob/master/images/favicon-inactive-384x384.png

Also for promotional tiles and og images, we'll be needing images of the following dimensions -
![image](https://user-images.githubusercontent.com/21277179/66235621-1fc3e100-e70e-11e9-8396-6a30b1ff3803.png)

**Comment by adityaketkar** [comment]
Hi. How about this one : 
![Screenshot_2019-10-04 Brandmark - make your logo in minutes](https://user-images.githubusercontent.com/22611315/66200691-43136f80-e6bf-11e9-9568-845c19284ad8.png)

**Comment by adityaketkar** [comment]
Or with a contrasting theme, like this : 
![Screenshot_2019-10-04 Brandmark - make your logo in minutes(1)](https://user-images.githubusercontent.com/22611315/66201023-f3817380-e6bf-11e9-8d73-c4f9922b7729.png)

**Comment by prateek3255** [comment]
The first one looks fantastic, @adityaketkar. We can use it for the og image

**Comment by ShreyaPrasad1209** [comment]
What about this one?
![Scrroll Inn (1)](https://user-images.githubusercontent.com/43600306/66235623-218da480-e70e-11e9-9cf8-46a036498471.png)

**Comment by prateek3255** [comment]
@adityaketkar I have updated the issue with the proper required dimensions.

**Comment by adityaketkar** [comment]
> @adityaketkar I have updated the issue with the proper required dimensions.
Great. I'll create two different icons using the mouse in the first picture.

**Comment by prateek3255** [comment]
@ShreyaPrasad1209 your icon won't be visible in the extension bar, please take a look at the dimensions mentioned in the issue.

**Comment by Neilblaze** [comment]
Have a look at this one!

![scroll in](https://user-images.githubusercontent.com/48355572/66240490-6cadb480-e71a-11e9-8834-bf14fc675095.jpg)

**Comment by Neilblaze** [comment]
**Have a look at this one :)**

![Scrolpng](https://user-images.githubusercontent.com/48355572/66240631-cf06b500-e71a-11e9-974e-0e81ea0930c0.png)

**Comment by Neilblaze** [comment]
Have a look at this one :)
![Scrolpng](https://user-images.githubusercontent.com/48355572/66241003-a337ff00-e71b-11e9-826d-64283eb0b169.png)

**Comment by DEBSUBHRO** [comment]
![icon-256](https://user-images.githubusercontent.com/42496309/66250306-8113a080-e75e-11e9-8a26-4034380ea2ac.png)
![icon-256(inactive)](https://user-images.githubusercontent.com/42496309/66250307-8113a080-e75e-11e9-9469-6ec42897b503.png)

**Comment by adityaketkar** [comment]
> ![icon-256](https://user-images.githubusercontent.com/42496309/66250306-8113a080-e75e-11e9-8a26-4034380ea2ac.png)
> ![icon-256(inactive)](https://user-images.githubusercontent.com/42496309/66250307-8113a080-e75e-11e9-9469-6ec42897b503.png)
> 
> How about this?


This looks great!

**Comment by prateek3255** [comment]
@DEBSUBHRO The icon seems fine, but I think you should remove the glyphs above and below the icon, considering we have minimal space in the extension bar.

Just the mouse icon will do!

**Comment by DEBSUBHRO** [comment]
> @DEBSUBHRO The icon seems fine, but I think you should remove the glyphs above and below the icon, considering we have minimal space in the extension bar.
> 
> Just the mouse icon will do!

Okay. Check these:
[Icons.zip](https://github.com/devfolioco/scrroll-in/files/3693073/Icons.zip)

**Comment by prateek3255** [comment]
> Okay. Check these:
Icons.zip

@DEBSUBHRO LGTM. Please open a PR for it.

**Comment by saisrinivaspaila** [comment]
Check out this PR with [Extension Logo](https://github.com/devfolioco/scrroll-in/pull/21)

**Comment by prateek3255** [comment]
Updated the icon and og-image thanks to @adityaketkar and @DEBSUBHRO 🙌
