### ISSUE TITLE
Update project documentation

### ISSUE THREAD

**Issue by jddeep** [devfolioco/scrroll-in#20]
Update License section in Readme file.

- **Steps to reproduce the issue**:

Currently, there is no 'License' section. This can be reformed into a correct structure for License showcasing like other substantial projects.

- **Relevant error messages and/or screenshots**:

Check the current Readme file.

**Comment by jddeep** [comment]
@prateek3255 Can I work on this please?

**Comment by prateek3255** [comment]
Please take a look at #32
