### ISSUE TITLE
Shift Entire Codebase from ES5 to ES6.

### ISSUE THREAD

**Issue by shikharsaxena98** [devfolioco/scrroll-in#23]
The codebase should be updated to use ES6 features. The current codebase is mixed with ES5 and ES6 syntax and practices. 
The following needs to done

1. Change all usages of 'var' keyword with 'let' or 'const'.
2. Using promises instead of callbacks.

**Comment by kohli6010** [comment]
I am not seeing anything which can be changed to ES6 promises

**Comment by shikharsaxena98** [comment]
Callback functions are being used in the Chrome API, we can change them to promises.

**Comment by wale-bant** [comment]
Hi, can i work on this?

**Comment by kohli6010** [comment]
Thanks for that @shikharsaxena98

**Comment by darkmatter18** [comment]
Is this issue closed? Can I work on it?

**Comment by shikharsaxena98** [comment]
@darkmatter18 & @wale-bant  , I think @kohli6010 is working on this, else you can work on this.
