### ISSUE TITLE
Omit query params from URL before saving in chrome local storage API.

### ISSUE THREAD

**Issue by itaditya** [devfolioco/scrroll-in#25]
**Is your feature request related to a problem? Please describe.**
Currently if you go to say example.com and save your scroll position. Next time you go to example.com?utm_param=something, then also the page should scroll to the saved position.

Since we are using `window.location.href`, the key generated with and without query params will be different.

**Describe the solution you'd like**

**Additional context**
Useful when you opened a URL which has bunch of tracking parameters.

@prateek3255 I'd love to work on this, if you think this is legit.

**Comment by prateek3255** [comment]
Yeah I know, I was going to open an issue for it.

**Comment by prateek3255** [comment]
> @prateek3255 I'd love to work on this if you think this is legit.
Go ahead! I'll assign this issue to you.

**Comment by itaditya** [comment]
@prateek3255 is there any changes needed?
