### ISSUE TITLE
Add an options page to view all the saved pages

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#3]
Create an [options page](https://developer.chrome.com/extensions/options) to view all the pages whose scroll positions have been saved.

Internally this extension uses the key `scroll-mark` as the key to store the URLs with their saved scroll position in the form of an object.

Where URL is the key, and the scroll position is the value. Something like this - 

```
scroll-mark: {
    "something.com/nothing":1440,
    ...
}
```

So you can read this object from the chrome's local storage and display all the saved URLs on the options page.

**Comment by N7Layla** [comment]
Hey, I'd love to give this a try!
