### ISSUE TITLE
Redesign the popup sheet

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#35]
Redesign the popup sheet to make it look something like this - 
![image](https://user-images.githubusercontent.com/21277179/66524032-ee348680-eb0e-11e9-84e1-b08eea793eba.png)

The settings button would redirect the user to the options page similar to the current options button.

**Resources**
- Use this [mockup](https://www.figma.com/file/GGHxsmNS9AhOq4Y1Co9wkT/Untitled?node-id=0%3A1) for detailed styles. 
- Get the settings icon from [here](https://feathericons.com/?query=settings)

**Comment by yordanzhelevdev** [comment]
I can do this

**Comment by Swayamsvk** [comment]
Can I work on this?

**Comment by prateek3255** [comment]
Sure go ahead @yordanzhelevdev @Swayamsvk
