### ISSUE TITLE
Investigate why the icon doesn't appear in the chrome extension menu

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#45]
**Describe the bug**
The extension icon doesn't appear in the chrome extension menu

**To Reproduce**
1. Go to chrome://extensions
2. The extension icon is not visible in the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/21277179/66706716-e87bb280-ed53-11e9-83c5-36875fba4e5c.png)

**Comment by MitchMo** [comment]
Took a quick stab at this and was able to find the solution. It appears "icons" was nested one object too deep in the manifest.json. By moving that out into the root, the icons began appearing
