### ISSUE TITLE
Unable to save scroll position of some URLs

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#66]
**Describe the bug**
Investigate why the extension is unable to save the scroll position of some URLs like - https://www.theguardian.com/technology/2008/mar/09/blogs

**To Reproduce**
1. Go to https://www.theguardian.com/technology/2008/mar/09/blogs
2. Click on the extension icon and save scroll
3. Click on the extension icon again
4. The scroll position is not saved.

**Additional context**
Investigate the issue here.

**Comment by CapitanFindusFI** [comment]
I think I'll have a go on this
