### ISSUE TITLE
Use babel for converting ES6 to ES5 and minify files

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#71]
The extension is using a combination of ES6 in a lot of places, and some old browsers (chrome 51 and below) don't support ES6. 
So, create a setup to transform ES6 to ES5 using babel and minify these files by running uglify some uglify tasks using gulp or grunt.

**Comment by Alucard17** [comment]
hey @prateek3255 I think webpack would be more futureproof.
