### ISSUE TITLE
Improve the options page

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#9]
The current options page shows all the URLs whose scroll positions have been saved. It currently looks like this -

![image](https://user-images.githubusercontent.com/21277179/66234664-e0949080-e70b-11e9-99f4-9f7ff9f58216.png)

You can find the HTML, CSS and JavaScript files for options page in [options.html](https://github.com/devfolioco/scrroll-in/blob/master/options.html), [options.css](https://github.com/devfolioco/scrroll-in/blob/master/options.css) and [options.js](https://github.com/devfolioco/scrroll-in/blob/master/options.js) respectively.

**Comment by fabrizvi** [comment]
Hey, can I work on this?

**Comment by prateek3255** [comment]
Yeah sure go ahead @fabrizvi
